"""
APEX CSV Sample Pipeline - Medallion Architecture Demo
=======================================================
A self-contained, working DAG that demonstrates the APEX medallion architecture
(Landing → Bronze → Silver → Gold) using a simple CSV dataset.

Runs entirely on LocalExecutor using PythonOperator + pandas.
No external Spark/Dataproc dependency required.

Generated by APEX Data Engineering Platform.
"""

from datetime import datetime, timedelta
import json
import os
import logging
import tempfile

from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.utils.trigger_rule import TriggerRule

logger = logging.getLogger(__name__)

# =============================================================================
# CONFIGURATION (from environment - metadata-driven)
# =============================================================================
DAG_ID = "apex_csv_sample_pipeline"
FEED_ID = "FEED_CSV_SAMPLE_001"

GCP_PROJECT = os.environ.get("GCP_PROJECT_ID", "agent-ai-test-461120")
GCS_RAW = os.environ.get("GCS_BUCKET_RAW", f"{GCP_PROJECT}-raw-data")
GCS_BRONZE = os.environ.get("GCS_BUCKET_BRONZE", f"{GCP_PROJECT}-bronze")
GCS_SILVER = os.environ.get("GCS_BUCKET_SILVER", f"{GCP_PROJECT}-silver")
GCS_GOLD = os.environ.get("GCS_BUCKET_GOLD", f"{GCP_PROJECT}-gold")

BQ_DATASET = os.environ.get("BIGQUERY_DATASET", "data_warehouse")
BQ_LOCATION = os.environ.get("BIGQUERY_LOCATION", "US")

default_args = {
    "owner": "apex-data-agent",
    "depends_on_past": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=2),
    "execution_timeout": timedelta(minutes=30),
}


# =============================================================================
# TASK FUNCTIONS (Self-contained - no external imports required)
# =============================================================================


def init_execution(**context):
    """Initialize execution context and create batch_id."""
    import uuid

    batch_id = context["ds_nodash"]
    run_id = str(uuid.uuid4())[:8]

    execution_context = {
        "feed_id": FEED_ID,
        "batch_id": batch_id,
        "run_id": run_id,
        "dag_id": DAG_ID,
        "start_time": datetime.utcnow().isoformat(),
        "zones_completed": [],
    }

    logger.info(f"[APEX] Initialized execution: feed={FEED_ID} batch={batch_id} run={run_id}")
    context["ti"].xcom_push(key="execution_context", value=json.dumps(execution_context))
    return execution_context


def create_sample_csv(**context):
    """Create a sample CSV and upload to GCS landing zone."""
    import pandas as pd
    from google.cloud import storage

    batch_id = context["ds_nodash"]

    # Create sample sales data
    data = {
        "order_id": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
        "customer_id": ["C001", "C002", "C001", "C003", "C002", "C004", "C001", "C005", "C003", "C002"],
        "customer_name": ["Alice Johnson", "Bob Smith", "Alice Johnson", "Charlie Brown", "Bob Smith",
                          "Diana Prince", "Alice Johnson", "Eve Wilson", "Charlie Brown", "Bob Smith"],
        "product": ["Widget A", "Widget B", "Widget C", "Widget A", "Widget A",
                     "Widget B", "Widget B", "Widget C", "Widget A", "Widget C"],
        "quantity": [2, 1, 3, 1, 4, 2, 1, 5, 2, 3],
        "unit_price": [29.99, 49.99, 19.99, 29.99, 29.99, 49.99, 49.99, 19.99, 29.99, 19.99],
        "order_date": [
            "2026-02-01", "2026-02-01", "2026-02-02", "2026-02-02", "2026-02-03",
            "2026-02-03", "2026-02-04", "2026-02-04", "2026-02-05", "2026-02-05",
        ],
        "region": ["US-East", "US-West", "US-East", "EU-West", "US-West",
                    "EU-East", "US-East", "APAC", "EU-West", "US-West"],
        "status": ["completed", "completed", "completed", "pending", "completed",
                    "completed", "returned", "completed", "completed", "completed"],
    }

    df = pd.DataFrame(data)

    # Upload to GCS landing zone
    client = storage.Client()
    bucket = client.bucket(GCS_RAW)
    blob_path = f"landing/{FEED_ID}/{batch_id}/sales_orders.csv"
    blob = bucket.blob(blob_path)

    csv_content = df.to_csv(index=False)
    blob.upload_from_string(csv_content, content_type="text/csv")

    record_count = len(df)
    gcs_path = f"gs://{GCS_RAW}/{blob_path}"

    logger.info(f"[APEX] Landing: Uploaded {record_count} records to {gcs_path}")
    context["ti"].xcom_push(key="landing_path", value=gcs_path)
    context["ti"].xcom_push(key="landing_records", value=record_count)

    return {"status": "success", "path": gcs_path, "records": record_count}


def landing_to_bronze(**context):
    """Bronze zone: Type casting, add audit columns, schema enforcement."""
    import pandas as pd
    from google.cloud import storage

    batch_id = context["ds_nodash"]

    # Read from landing
    client = storage.Client()
    bucket_raw = client.bucket(GCS_RAW)
    blob = bucket_raw.blob(f"landing/{FEED_ID}/{batch_id}/sales_orders.csv")
    csv_content = blob.download_as_text()

    df = pd.read_csv(pd.io.common.StringIO(csv_content))

    # Bronze transformations: type casting + audit columns
    df["quantity"] = df["quantity"].astype("int64")
    df["unit_price"] = df["unit_price"].astype("float64")
    df["order_date"] = pd.to_datetime(df["order_date"])

    # Add audit columns (APEX standard)
    df["_ingestion_timestamp"] = datetime.utcnow().isoformat()
    df["_batch_id"] = batch_id
    df["_source_file"] = f"landing/{FEED_ID}/{batch_id}/sales_orders.csv"
    df["_feed_id"] = FEED_ID

    # Write to bronze zone as parquet
    bucket_bronze = client.bucket(GCS_BRONZE)
    parquet_path = f"bronze/{FEED_ID}/{batch_id}/sales_orders.parquet"
    blob_out = bucket_bronze.blob(parquet_path)

    with tempfile.NamedTemporaryFile(suffix=".parquet") as tmp:
        df.to_parquet(tmp.name, index=False)
        blob_out.upload_from_filename(tmp.name)

    gcs_path = f"gs://{GCS_BRONZE}/{parquet_path}"
    logger.info(f"[APEX] Bronze: {len(df)} records with audit columns → {gcs_path}")
    context["ti"].xcom_push(key="bronze_path", value=gcs_path)
    context["ti"].xcom_push(key="bronze_records", value=len(df))

    return {"status": "success", "path": gcs_path, "records": len(df)}


def bronze_to_silver(**context):
    """Silver zone: Data cleaning, deduplication, null handling, standardization."""
    import pandas as pd
    from google.cloud import storage

    batch_id = context["ds_nodash"]

    # Read from bronze
    client = storage.Client()
    bucket_bronze = client.bucket(GCS_BRONZE)
    blob = bucket_bronze.blob(f"bronze/{FEED_ID}/{batch_id}/sales_orders.parquet")

    with tempfile.NamedTemporaryFile(suffix=".parquet") as tmp:
        blob.download_to_filename(tmp.name)
        df = pd.read_parquet(tmp.name)

    records_before = len(df)

    # Silver transformations
    # 1. Remove duplicates by order_id
    df = df.drop_duplicates(subset=["order_id"], keep="first")

    # 2. Filter out non-completed orders
    df = df[df["status"] == "completed"].copy()

    # 3. Standardize region names
    df["region"] = df["region"].str.upper().str.strip()

    # 4. Calculate total_amount
    df["total_amount"] = df["quantity"] * df["unit_price"]

    # 5. Standardize customer_name (title case)
    df["customer_name"] = df["customer_name"].str.title()

    records_after = len(df)

    # Write to silver zone
    bucket_silver = client.bucket(GCS_SILVER)
    parquet_path = f"silver/{FEED_ID}/{batch_id}/sales_orders_clean.parquet"
    blob_out = bucket_silver.blob(parquet_path)

    with tempfile.NamedTemporaryFile(suffix=".parquet") as tmp:
        df.to_parquet(tmp.name, index=False)
        blob_out.upload_from_filename(tmp.name)

    gcs_path = f"gs://{GCS_SILVER}/{parquet_path}"
    logger.info(f"[APEX] Silver: {records_before} → {records_after} records (cleaned) → {gcs_path}")
    context["ti"].xcom_push(key="silver_path", value=gcs_path)
    context["ti"].xcom_push(key="silver_records", value=records_after)

    return {"status": "success", "path": gcs_path, "records_in": records_before, "records_out": records_after}


def silver_to_gold(**context):
    """Gold zone: Business aggregations, analytics-ready dataset."""
    import pandas as pd
    from google.cloud import storage

    batch_id = context["ds_nodash"]

    # Read from silver
    client = storage.Client()
    bucket_silver = client.bucket(GCS_SILVER)
    blob = bucket_silver.blob(f"silver/{FEED_ID}/{batch_id}/sales_orders_clean.parquet")

    with tempfile.NamedTemporaryFile(suffix=".parquet") as tmp:
        blob.download_to_filename(tmp.name)
        df = pd.read_parquet(tmp.name)

    # Gold transformations: Business aggregations

    # 1. Customer summary (aggregation)
    customer_summary = df.groupby(["customer_id", "customer_name"]).agg(
        total_orders=("order_id", "count"),
        total_quantity=("quantity", "sum"),
        total_revenue=("total_amount", "sum"),
        avg_order_value=("total_amount", "mean"),
        first_order=("order_date", "min"),
        last_order=("order_date", "max"),
    ).reset_index()

    customer_summary["_batch_id"] = batch_id
    customer_summary["_computed_at"] = datetime.utcnow().isoformat()

    # 2. Product summary
    product_summary = df.groupby(["product"]).agg(
        total_sold=("quantity", "sum"),
        total_revenue=("total_amount", "sum"),
        unique_customers=("customer_id", "nunique"),
        avg_price=("unit_price", "mean"),
    ).reset_index()

    product_summary["_batch_id"] = batch_id
    product_summary["_computed_at"] = datetime.utcnow().isoformat()

    # Write to gold zone
    bucket_gold = client.bucket(GCS_GOLD)

    # Customer summary
    cust_path = f"gold/{FEED_ID}/{batch_id}/customer_summary.parquet"
    blob_cust = bucket_gold.blob(cust_path)
    with tempfile.NamedTemporaryFile(suffix=".parquet") as tmp:
        customer_summary.to_parquet(tmp.name, index=False)
        blob_cust.upload_from_filename(tmp.name)

    # Product summary
    prod_path = f"gold/{FEED_ID}/{batch_id}/product_summary.parquet"
    blob_prod = bucket_gold.blob(prod_path)
    with tempfile.NamedTemporaryFile(suffix=".parquet") as tmp:
        product_summary.to_parquet(tmp.name, index=False)
        blob_prod.upload_from_filename(tmp.name)

    logger.info(f"[APEX] Gold: {len(customer_summary)} customers, {len(product_summary)} products → gs://{GCS_GOLD}/gold/{FEED_ID}/{batch_id}/")

    context["ti"].xcom_push(key="gold_customer_path", value=f"gs://{GCS_GOLD}/{cust_path}")
    context["ti"].xcom_push(key="gold_product_path", value=f"gs://{GCS_GOLD}/{prod_path}")
    context["ti"].xcom_push(key="gold_customer_records", value=len(customer_summary))
    context["ti"].xcom_push(key="gold_product_records", value=len(product_summary))

    return {
        "status": "success",
        "customers": len(customer_summary),
        "products": len(product_summary),
    }


def load_to_bigquery(**context):
    """Load gold datasets to BigQuery for analytics."""
    import pandas as pd
    from google.cloud import storage, bigquery

    batch_id = context["ds_nodash"]

    bq_client = bigquery.Client(project=GCP_PROJECT, location=BQ_LOCATION)
    gcs_client = storage.Client()

    # Ensure dataset exists
    dataset_ref = bigquery.DatasetReference(GCP_PROJECT, BQ_DATASET)
    try:
        bq_client.get_dataset(dataset_ref)
    except Exception:
        dataset = bigquery.Dataset(dataset_ref)
        dataset.location = BQ_LOCATION
        bq_client.create_dataset(dataset, exists_ok=True)
        logger.info(f"[APEX] Created BigQuery dataset: {BQ_DATASET}")

    # Load customer_summary
    bucket_gold = gcs_client.bucket(GCS_GOLD)

    cust_blob = bucket_gold.blob(f"gold/{FEED_ID}/{batch_id}/customer_summary.parquet")
    with tempfile.NamedTemporaryFile(suffix=".parquet") as tmp:
        cust_blob.download_to_filename(tmp.name)
        df_cust = pd.read_parquet(tmp.name)

    # Convert datetime columns to string for BQ compatibility
    for col in df_cust.select_dtypes(include=["datetime64"]).columns:
        df_cust[col] = df_cust[col].astype(str)

    table_id = f"{GCP_PROJECT}.{BQ_DATASET}.customer_summary"
    job_config = bigquery.LoadJobConfig(write_disposition="WRITE_TRUNCATE")
    job = bq_client.load_table_from_dataframe(df_cust, table_id, job_config=job_config)
    job.result()
    logger.info(f"[APEX] BigQuery: Loaded {len(df_cust)} rows → {table_id}")

    # Load product_summary
    prod_blob = bucket_gold.blob(f"gold/{FEED_ID}/{batch_id}/product_summary.parquet")
    with tempfile.NamedTemporaryFile(suffix=".parquet") as tmp:
        prod_blob.download_to_filename(tmp.name)
        df_prod = pd.read_parquet(tmp.name)

    table_id_prod = f"{GCP_PROJECT}.{BQ_DATASET}.product_summary"
    job = bq_client.load_table_from_dataframe(df_prod, table_id_prod, job_config=job_config)
    job.result()
    logger.info(f"[APEX] BigQuery: Loaded {len(df_prod)} rows → {table_id_prod}")

    return {
        "status": "success",
        "tables_loaded": [table_id, table_id_prod],
    }


def finalize_execution(**context):
    """Finalize execution - collect metrics and log completion."""
    ti = context["ti"]
    batch_id = context["ds_nodash"]

    landing_records = ti.xcom_pull(key="landing_records") or 0
    bronze_records = ti.xcom_pull(key="bronze_records") or 0
    silver_records = ti.xcom_pull(key="silver_records") or 0
    gold_customers = ti.xcom_pull(key="gold_customer_records") or 0
    gold_products = ti.xcom_pull(key="gold_product_records") or 0

    summary = {
        "feed_id": FEED_ID,
        "dag_id": DAG_ID,
        "batch_id": batch_id,
        "status": "SUCCESS",
        "zones": {
            "landing": {"records": landing_records},
            "bronze": {"records": bronze_records},
            "silver": {"records": silver_records},
            "gold": {
                "customer_summary": gold_customers,
                "product_summary": gold_products,
            },
        },
        "completed_at": datetime.utcnow().isoformat(),
    }

    logger.info(f"[APEX] Pipeline complete: {json.dumps(summary, indent=2)}")
    return summary


# =============================================================================
# DAG DEFINITION
# =============================================================================

with DAG(
    dag_id=DAG_ID,
    default_args=default_args,
    description="APEX CSV Sample Pipeline - Medallion Architecture (Landing → Bronze → Silver → Gold → BigQuery)",
    schedule="@daily",
    start_date=datetime(2026, 2, 7),
    catchup=False,
    max_active_runs=1,
    tags=["apex", "csv", "medallion", "sample", "gcs", "bigquery"],
) as dag:

    t_init = PythonOperator(
        task_id="init_execution",
        python_callable=init_execution,
    )

    t_landing = PythonOperator(
        task_id="create_sample_csv_landing",
        python_callable=create_sample_csv,
    )

    t_bronze = PythonOperator(
        task_id="landing_to_bronze",
        python_callable=landing_to_bronze,
    )

    t_silver = PythonOperator(
        task_id="bronze_to_silver",
        python_callable=bronze_to_silver,
    )

    t_gold = PythonOperator(
        task_id="silver_to_gold",
        python_callable=silver_to_gold,
    )

    t_bq = PythonOperator(
        task_id="load_to_bigquery",
        python_callable=load_to_bigquery,
    )

    t_finalize = PythonOperator(
        task_id="finalize_execution",
        python_callable=finalize_execution,
        trigger_rule=TriggerRule.ALL_SUCCESS,
    )

    # Task dependencies: Medallion flow
    t_init >> t_landing >> t_bronze >> t_silver >> t_gold >> t_bq >> t_finalize
