"""
sample_csv_ingest_dag - File Ingest Pipeline

Pipeline: sample_csv_ingest
Domain: sales
Environment: dev
Source: gs://landing-zone/sales/sample_data.csv
Schedule: @daily

FLOW:
1. Sense for new files in landing zone
2. Run bronze ingest (raw data loading)
3. Run silver transform (cleansing, dedup)
4. Run gold load to BigQuery
5. Cleanup and notify

Generated by Data Agent
Jira: N/A
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.operators.empty import EmptyOperator
from airflow.providers.google.cloud.operators.dataproc import DataprocSubmitJobOperator
from airflow.providers.google.cloud.sensors.gcs import GCSObjectsWithPrefixExistenceSensor
from airflow.utils.task_group import TaskGroup


# Configuration
PROJECT_ID = "{{ var.value.gcp_project_id }}"
REGION = "{{ var.value.gcp_region }}"
CLUSTER_NAME = "{{ var.value.dataproc_cluster }}"

# Paths
LANDING_PATH = "gs://landing-zone/sales/sample_data.csv"
BRONZE_PATH = "gs://bronze/sample_csv_ingest"
SILVER_PATH = "gs://silver/sample_csv_ingest"
GOLD_PATH = "gs://gold/sample_csv_ingest"

# Spark job URIs
BRONZE_JOB_URI = "gs://spark-jobs/bronze_ingest.py"
SILVER_JOB_URI = "gs://spark-jobs/silver_transform.py"
GOLD_JOB_URI = "gs://spark-jobs/gold_load_bq.py"

default_args = {
    "owner": "data-engineering",
    "depends_on_past": False,
    "email_on_failure": True,
    "email_on_retry": False,
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
    "execution_timeout": timedelta(hours=2),
}


def _build_pyspark_job(main_python_file_uri: str, args: list = None) -> dict:
    """Build Dataproc PySpark job configuration."""
    return {
        "placement": {"cluster_name": CLUSTER_NAME},
        "pyspark_job": {
            "main_python_file_uri": main_python_file_uri,
            "args": args or [],
            "properties": {
                "spark.sql.adaptive.enabled": "true",
                "spark.sql.adaptive.coalescePartitions.enabled": "true",
            },
        },
    }


with DAG(
    dag_id="sample_csv_ingest_dag",
    default_args=default_args,
    description="File ingest pipeline for sample_csv_ingest - sales",
    schedule="@daily",
    start_date=datetime.strptime("2024-01-01", "%Y-%m-%d"),
    catchup=False,
    max_active_runs=1,
    tags=["sales", "dev", "data-platform"],
    doc_md=__doc__,
) as dag:

    # Start task
    start = EmptyOperator(task_id="start")

    # Wait for new files in landing zone
    wait_for_files = GCSObjectsWithPrefixExistenceSensor(
        task_id="wait_for_files",
        bucket="landing-zone",
        prefix="sales/sample_data.csv",
        google_cloud_conn_id="google_cloud_default",
        mode="poke",
        poke_interval=60,
        timeout=3600,  # 1 hour timeout
    )

    # Bronze Layer - Raw Data Ingestion
    with TaskGroup(group_id="bronze_layer") as bronze_layer:
        bronze_ingest = DataprocSubmitJobOperator(
            task_id="bronze_ingest",
            project_id=PROJECT_ID,
            region=REGION,
            job=_build_pyspark_job(
                BRONZE_JOB_URI,
                args=[
                    "--source-path", LANDING_PATH,
                    "--target-table", "bronze.sales.sample_data",
                    "--file-format", "csv",
                    "--execution-date", "{{ ds }}",
                ],
            ),
        )

    # Silver Layer - Cleansing and Transformation
    with TaskGroup(group_id="silver_layer") as silver_layer:
        silver_transform = DataprocSubmitJobOperator(
            task_id="silver_transform",
            project_id=PROJECT_ID,
            region=REGION,
            job=_build_pyspark_job(
                SILVER_JOB_URI,
                args=[
                    "--source-table", "bronze.sales.sample_data",
                    "--target-table", "silver.sales.sample_data",
                    "--execution-date", "{{ ds }}",
                ],
            ),
        )

    # Gold Layer - Load to BigQuery
    with TaskGroup(group_id="gold_layer") as gold_layer:
        gold_load_bq = DataprocSubmitJobOperator(
            task_id="gold_load_bq",
            project_id=PROJECT_ID,
            region=REGION,
            job=_build_pyspark_job(
                GOLD_JOB_URI,
                args=[
                    "--source-table", "silver.sales.sample_data",
                    "--bq-dataset", "sales",
                    "--bq-table", "sample_csv_ingest",
                    "--execution-date", "{{ ds }}",
                ],
            ),
        )

    # End task
    end = EmptyOperator(task_id="end")

    # Define task dependencies
    start >> wait_for_files >> bronze_layer >> silver_layer >> gold_layer >> end
