"""
sample_csv_ingest_dag - File Ingest Pipeline

Pipeline: sample_csv_ingest
Domain: sales
Environment: dev
Source: gs://landing-zone/sales/sample_data.csv
Schedule: @daily

Generated by Data Agent
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.operators.empty import EmptyOperator

# Try to import GCP providers, fall back gracefully
try:
    from airflow.providers.google.cloud.operators.dataproc import DataprocSubmitJobOperator
    from airflow.providers.google.cloud.sensors.gcs import GCSObjectsWithPrefixExistenceSensor
    HAS_GCP_PROVIDERS = True
except ImportError:
    HAS_GCP_PROVIDERS = False


# Configuration
PROJECT_ID = "{{ var.value.gcp_project_id }}"
REGION = "{{ var.value.gcp_region }}"
CLUSTER_NAME = "{{ var.value.dataproc_cluster }}"

LANDING_PATH = "gs://landing-zone/sales/sample_data.csv"
BRONZE_PATH = "gs://bronze/sample_csv_ingest"
SILVER_PATH = "gs://silver/sample_csv_ingest"
GOLD_PATH = "gs://gold/sample_csv_ingest"

BRONZE_JOB_URI = "gs://spark-jobs/bronze_ingest.py"
SILVER_JOB_URI = "gs://spark-jobs/silver_transform.py"
GOLD_JOB_URI = "gs://spark-jobs/gold_load_bq.py"

default_args = {
    "owner": "data-engineering",
    "depends_on_past": False,
    "email_on_failure": True,
    "email_on_retry": False,
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
    "execution_timeout": timedelta(hours=2),
}


def _log_info(message: str, **context):
    """Log task execution info."""
    print(f"[{datetime.now().isoformat()}] {message}")
    return message


with DAG(
    dag_id="sample_csv_ingest_dag",
    default_args=default_args,
    description="File ingest pipeline for sales domain",
    schedule="@daily",
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["sales", "dev", "data-platform", "file-ingest"],
    max_active_runs=1,
) as dag:

    start = EmptyOperator(task_id="start")
    
    log_start = PythonOperator(
        task_id="log_pipeline_start",
        python_callable=_log_info,
        op_args=["Starting sample_csv_ingest pipeline"],
    )
    
    bronze_ingest = PythonOperator(
        task_id="bronze_ingest",
        python_callable=_log_info,
        op_args=[f"Bronze ingest from {LANDING_PATH}"],
    )
    
    silver_transform = PythonOperator(
        task_id="silver_transform",
        python_callable=_log_info,
        op_args=[f"Silver transform to {SILVER_PATH}"],
    )
    
    gold_load = PythonOperator(
        task_id="gold_load_to_bigquery",
        python_callable=_log_info,
        op_args=[f"Gold load to {GOLD_PATH}"],
    )
    
    log_end = PythonOperator(
        task_id="log_pipeline_complete",
        python_callable=_log_info,
        op_args=["Pipeline complete"],
    )
    
    end = EmptyOperator(task_id="end")

    # Define task dependencies
    start >> log_start >> bronze_ingest >> silver_transform >> gold_load >> log_end >> end
